backend = "glx";
paint-on-overlay = true;
glx-no-stencil = true;
vsync = "opengl-swc";

# Shadow
shadow = true; # Enabled client-side shadows on windows.
no-dock-shadow = true; # Avoid drawing shadows on dock/panel windows.
no-dnd-shadow = true; # Don't draw shadows on DND windows.
clear-shadow = true; # Zero the part of the shadow's mask behind the window (experimental).
shadow-radius = 7; # The blur radius for shadows. (default 12)
shadow-offset-x = -7; # The left offset for shadows. (default -15)
shadow-offset-y = -7; # The top offset for shadows. (default -15)
# shadow-exclude = [
#  "n:e:Notification",
#  "n:e:Docky",
#  "g:e:Synapse",
#  "g:e:Conky",
#  "n:w:*Firefox*",
#  "n:w:*Chromium*",
#  "n:w:*dockbarx*",
#  "class_g ?= 'Cairo-dock'",
#  "class_g ?= 'Xfce4-notifyd'",
#  "class_g ?= 'Xfce4-power-manager'",
#  "class_g ?= 'Notify-osd'",
#  "_GTK_FRAME_EXTENTS@:c"
# ];

# Opacity
detect-client-opacity = true;
# Menu and Inactice Opacity
menu-opacity = 0.90;
inactive-opacity = 0.93;

# Fading
fading = true;
fade-delta = 4;
fade-in-step = 0.018;
fade-out-step = 0.015;
#fade-in-step = 0.036;
#fade-out-step = 0.040;
# no-fading-openclose = true;
# no-fading-destroyed-argb = true;
fade-exclude = [ ];

# Window type settings
wintypes:
{
 tooltip = { shadow = false; };
}

opacity-rule = [ "94:class_g = 'Emacs'", "99:class_g = 'dmenu'" ];